### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by feschmidt** [steelelab-delft/stlabutils#5]
integration with Travis CI without packaging seems very tricky:

- when using `python3 tests/test_testing.py`, travis doesn't find stanalysis
```
$ python3 tests/test_testing.py
Traceback (most recent call last):
  File "tests/test_testing.py", line 2, in <module>
    import stanalysis
ModuleNotFoundError: No module named 'stanalysis'
The command "python3 tests/test_testing.py" exited with 1.
```
- when using `python3 -m tests/test_testing.py`, travis returns `Error while finding module specification for 'tests/test_testing.py' (ModuleNotFoundError: No module named 'tests/test_testing')`. The same happens on my local machine

See also
- https://stackoverflow.com/questions/25756134/how-to-add-my-module-to-travis-ci-pythonpath
- https://python-packaging.readthedocs.io/en/latest/minimal.html
- https://github.com/pytest-dev/pytest/issues/2287
- https://github.com/pytest-dev/pytest/issues/2421

**Comment by feschmidt** [comment]
halted travis integration for now

**Comment by kennedy** [comment]
I experienced a similar issue. I am still figuring it out, but I gotten a bit further once I defined the PYTHONPATH env variable in my .travis.ci file.

```
script:
  - export PYTHONPATH=$(pwd)
```
