### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by feschmidt** [steelelab-delft/stlabutils#6]
What would be the best name?
- stlabutils: closest to original repo (stlab.utils), but might be cumbersome to type: `stlabutils.utils`
- stanalysis: not all about analysis
- stlabtools
- ...

**Comment by mgely** [comment]
you don't have to type stlabutils.utils: you can set up the __init__.py file such that people get all the functions from stlabutils.utils by importing stlabutils.

All you have to do is put from "stlabutils.utils import *" in the  __init__.py file
